version: '3.8'
services:
  db:
    image: postgres:14
    container_name: ckgcus_db
    environment:
      POSTGRES_DB: ckgcus
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 