[build-system]
requires = ["setuptools<64"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
force_single_line = false
combine_as_imports = true
